# Ansible Role: mongodb
# File: /molecule/replicaset-psa-ubi9/converge.yml
# Description: Managed by doc-sync workflow

---
# required for fact gathering, ipv4 address
- name: Converge
  hosts:
    - test-multi-01
    - test-multi-02
    - test-multi-03
  tasks:
    - name: install iproute
      dnf:
        name: iproute

    - name: Set mongodb_use_template_for_hosts
      set_fact:
        mongodb_use_template_for_hosts: "{{ mongodb_use_template_for_hosts | default(true) }}"

    - name: set /etc/hosts file
      template:
        src: hosts.j2
        dest: /etc/hosts
        mode: "0644"
        owner: root
        group: root
      when: mongodb_use_template_for_hosts | bool

- name: Converge
  hosts:
    - test-multi-01
    - test-multi-02
    - test-multi-03
  any_errors_fatal: true
  roles:
    - role: ../..
