---
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  name: default
dependency:
  name: galaxy
driver:
  name: docker
provisioner:
  name: ansible
verifier:
  name: ansible
platforms:
  - name: test-multi-01
    hostname: test-multi-01
    image: registry.access.redhat.com/ubi9/ubi:latest
    privileged: true
    pull: true
    command: "tail -f /dev/null"
    volumes:
      - "/var/lib/containerd"
    tmpfs:
      - /run
      - /tmp
    tty: true
    environment:
      container: docker
    pre_build_image: true
    networks:
      - name: test_network
