# Ansible Role: mongodb
# File: /molecule/default-ubi8/molecule.yml
# Description: Managed by doc-sync workflow

---
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  name: default-ubi8
dependency:
  name: galaxy
driver:
  name: docker
provisioner:
  name: ansible
  inventory:
    host_vars:
      test-ubi8-01:
        ansible_python_interpreter: /usr/bin/python3.9
verifier:
  name: ansible
platforms:
  - name: test-ubi8-01
    hostname: test-ubi8-01
    image: geerlingguy/docker-ubi8-ansible:latest
    privileged: true
    pull: true
    command: "/usr/sbin/init" # to use systemd
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tmpfs:
      - /run
      - /tmp
    tty: true
    environment:
      container: docker
    pre_build_image: true
    networks:
      - name: test_network
